// GENERATED by tools/holo-v86-9pfs.mjs — do not hand-edit; re-run to regenerate.
//
// The 9pfs κ seam for v86. v86's 9p filesystem (fs.json v3) addresses every file by its sha256:
// it reads file content from baseurl + <sha256sum>. So the filename IS the content address — this
// worker intercepts those reads, streams the bytes (canonical κ-route first, else the origin CDN —
// CORS-open), RE-DERIVES sha256 and refuses unless it equals the requested hash (Law L5, intrinsic),
// then serves. Only the small fs.json (the inode tree = the manifest) is sealed; the whole root
// filesystem streams + self-verifies on demand — a multi-hundred-MB OS costs ~KB of pinned state.

const SCOPE = new URL(self.registration.scope).pathname;
const PREFIX = SCOPE + "fs9p/";                 // v86's baseurl (app-relative) → /apps/<id>/fs9p/<sha256>
const ORIGIN = "__FILE_ORIGIN__";               // where the content-addressed files actually live (CDN)
const KAPPA_ROUTE = "/.holo/sha256/";

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));

const cache = new Map();
const stats = { files: 0, cacheHits: 0, bytes: 0, maxStallMs: 0, totalStallMs: 0, refused: 0 };
const toHex = (b) => [...new Uint8Array(b)].map((x) => x.toString(16).padStart(2, "0")).join("");

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(PREFIX)) return;
  event.respondWith(serve(url.pathname.slice(PREFIX.length)));
});

async function serve(rest) {
  // v86's file id is a sha256 PREFIX + ".bin" (e.g. 3961f1b5.bin). The sealed fs.json commits to these
  // prefixes; we re-derive the full sha256 and confirm it starts with the prefix (content-derived,
  // 32-bit). Not the full 256-bit L5 the disk formats get — this image's tree only carries prefixes.
  const key = rest.split("/").pop();
  const prefix = key.replace(/\.[^.]+$/, "");
  try {
    const hit = cache.get(key);
    if (hit) { stats.cacheHits++; return new Response(hit, { status: 200, headers: { "Content-Type": "application/octet-stream" } }); }
    const t0 = performance.now();
    const r = await fetch(ORIGIN + key, { cache: "force-cache" });   // stream the file by its id (CORS-open CDN)
    if (!r.ok) return new Response("9pfs " + key + " HTTP " + r.status, { status: 502 });
    const buf = await r.arrayBuffer();
    const got = toHex(await crypto.subtle.digest("SHA-256", buf));
    if (/^[0-9a-f]{4,}$/.test(prefix) && !got.startsWith(prefix)) { stats.refused++; return new Response("content-prefix mismatch (refused)", { status: 502 }); }
    const dt = performance.now() - t0;
    stats.files++; stats.bytes += buf.byteLength; stats.totalStallMs += dt; stats.maxStallMs = Math.max(stats.maxStallMs, dt);
    const bytes = new Uint8Array(buf);
    cache.set(key, bytes);
    return new Response(bytes, { status: 200, headers: { "Content-Type": "application/octet-stream", "Content-Length": String(bytes.length) } });
  } catch (e) { return new Response("9pfs error: " + (e && e.message || e), { status: 502 }); }
}

self.addEventListener("message", (event) => {
  const msg = event.data || {};
  if (msg.type === "kblocks-stats") {
    const avg = stats.files ? stats.totalStallMs / stats.files : 0;
    const data = { type: "kblocks-stats", blockFetches: stats.files, cacheHits: stats.cacheHits, bytes: stats.bytes,
      maxStallMs: stats.maxStallMs, avgStallMs: +avg.toFixed(2), refused: stats.refused };
    if (event.source) event.source.postMessage(data);
    else if (event.ports && event.ports[0]) event.ports[0].postMessage(data);
  }
});
