// GENERATED by tools/holo-v86-chunked.mjs — do not hand-edit; re-run to regenerate.
//
// The CHUNKED κ seam for v86 (manifest-only pin + lazy verified stream). v86's use_parts backend
// fetches a disk as a directory of fixed-size parts: <base><off>-<off+chunk><ext>. This worker
// intercepts those part GETs, maps the byte offset → chunk index → the part's pinned κ (from the
// sealed manifest), fetches the bytes (canonical κ-route first, else the origin CDN — CORS-open),
// RE-DERIVES sha256 and refuses on mismatch (Law L5), then serves them. v86 zstd-decompresses if
// the parts are compressed. Only the small manifest is sealed; parts stream + verify on demand, so
// a 700 MB OS costs ~KB of pinned state — 100% κ-addressable without pinning the whole image.

const SCOPE = new URL(self.registration.scope).pathname;
const MANIFEST_URL = SCOPE + "images/__MANIFEST_FILE__";
const KAPPA_ROUTE = "/.holo/sha256/";

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil((async () => { await self.clients.claim(); try { await loadManifest(); } catch (_) {} })()));

let M = null, manifestP = null, partRe = null;
const cache = new Map();
const stats = { parts: 0, cacheHits: 0, bytes: 0, maxStallMs: 0, totalStallMs: 0, refused: 0 };
const toHex = (b) => [...new Uint8Array(b)].map((x) => x.toString(16).padStart(2, "0")).join("");
const hexOf = (d) => String(d).split(":").pop();

function loadManifest() {
  if (!manifestP) manifestP = fetch(MANIFEST_URL, { cache: "no-store" }).then((r) => {
    if (!r.ok) throw new Error("chunked manifest HTTP " + r.status);
    return r.json();
  }).then((m) => {
    M = m;
    // part URL: <host><basename><off>-<off+chunk><ext> — match the "<off>-<end><ext>" tail.
    const ext = (m.ext || "").replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    partRe = new RegExp("(\\d+)-(\\d+)" + ext + "$");
    return m;
  });
  return manifestP;
}

async function fetchVerified(index, originalUrl) {
  const want = hexOf(M.parts[index]);
  if (!want) throw new Error("no κ for chunk " + index);
  const hit = cache.get(want);
  if (hit) { stats.cacheHits++; return hit; }
  const t0 = performance.now();
  let r = await fetch(KAPPA_ROUTE + want, { cache: "force-cache" });   // pinned κ-route first
  if (!r.ok) r = await fetch(originalUrl, { cache: "force-cache" });   // else stream from the CDN
  if (!r.ok) throw new Error("chunk " + index + " HTTP " + r.status);
  const buf = await r.arrayBuffer();
  const got = toHex(await crypto.subtle.digest("SHA-256", buf));
  if (got !== want) { stats.refused++; throw new Error("κ mismatch chunk " + index + " (refused, L5)"); }
  const dt = performance.now() - t0;
  stats.parts++; stats.bytes += buf.byteLength; stats.totalStallMs += dt; stats.maxStallMs = Math.max(stats.maxStallMs, dt);
  const bytes = new Uint8Array(buf);
  cache.set(want, bytes);
  return bytes;
}

loadManifest().catch(() => {});   // eager — ready before the guest ever reads the disk
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET" || !M) return;                   // before manifest loads, never intercept
  if (req.url.includes(M.basename) && partRe.test(req.url)) event.respondWith(handle(req));
});

async function handle(req) {
  try {
    await loadManifest();
    if (!(req.url.includes(M.basename) && partRe.test(req.url))) return fetch(req);   // not a part → passthrough
    const off = parseInt(partRe.exec(req.url)[1], 10);
    const index = Math.floor(off / M.chunkSize);
    const bytes = await fetchVerified(index, req.url);
    return new Response(bytes, { status: 200, headers: { "Content-Type": "application/octet-stream", "Content-Length": String(bytes.length) } });
  } catch (e) { return new Response("chunked κ error: " + (e && e.message || e), { status: 502 }); }
}

self.addEventListener("message", (event) => {
  const msg = event.data || {};
  if (msg.type === "kblocks-stats") {
    const avg = stats.parts ? stats.totalStallMs / stats.parts : 0;
    const data = { type: "kblocks-stats", blockFetches: stats.parts, cacheHits: stats.cacheHits, bytes: stats.bytes,
      maxStallMs: stats.maxStallMs, avgStallMs: +avg.toFixed(2), refused: stats.refused };
    if (event.source) event.source.postMessage(data);
    else if (event.ports && event.ports[0]) event.ports[0].postMessage(data);
  }
});
