// GENERATED by tools/holo-v86-ingest.mjs — do not hand-edit; re-run ingest to regenerate.
//
// The κ-BLOCK DISK seam for v86. v86's async disk backend reads the image one
// fixed_chunk_size-aligned range at a time over an XHR `Range` request and ABORTS on a 200.
// This worker intercepts those ranged reads on the image URL and answers each from the κ-block
// DAG: map offset → block index → block κ → fetch → re-derive sha256 (refuse on mismatch,
// Law L5) → 206 Partial Content. Only blocks the guest touches are ever fetched.
//
// Blocks resolve by κ: canonical OS-wide route (/.holo/sha256/<hex>) first — the route that
// relock-app folds the block objects into — with the app-relative store as a pre-reindex fallback.

const SCOPE = new URL(self.registration.scope).pathname;
const IMAGE_FILE = "__IMAGE_FILE__";
const MANIFEST_URL = SCOPE + "images/" + IMAGE_FILE + ".kblocks.json";
const IMAGE_PATH = SCOPE + "images/" + IMAGE_FILE;
const KAPPA_ROUTE = "/.holo/sha256/";
const STORE_FALLBACK = SCOPE + "images/" + IMAGE_FILE + ".kblocks/.holo/sha256/";

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(self.clients.claim()));

let manifestP = null;
const blockCache = new Map();
const stats = { reads: 0, blockFetches: 0, cacheHits: 0, bytes: 0, maxStallMs: 0, totalStallMs: 0 };
const hexOf = (did) => String(did).split(":").pop();
const toHex = (buf) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");

function loadManifest() {
  if (!manifestP) manifestP = fetch(MANIFEST_URL, { cache: "no-store" }).then((r) => {
    if (!r.ok) throw new Error("kblocks manifest HTTP " + r.status); return r.json();
  });
  return manifestP;
}
async function getBlock(hex) {
  const cached = blockCache.get(hex);
  if (cached) { stats.cacheHits++; return cached; }
  const t0 = performance.now();
  let r = await fetch(KAPPA_ROUTE + hex, { cache: "force-cache" });
  if (!r.ok) r = await fetch(STORE_FALLBACK + hex, { cache: "force-cache" });
  if (!r.ok) throw new Error("block " + hex.slice(0, 10) + " HTTP " + r.status);
  const buf = await r.arrayBuffer();
  const actual = toHex(await crypto.subtle.digest("SHA-256", buf));
  if (actual !== hex) throw new Error("κ mismatch on block " + hex.slice(0, 10) + " (refused, Law L5)");
  const dt = performance.now() - t0;
  stats.blockFetches++; stats.totalStallMs += dt; stats.maxStallMs = Math.max(stats.maxStallMs, dt);
  const bytes = new Uint8Array(buf); blockCache.set(hex, bytes); return bytes;
}
function prefetch(blocks, fromIndex, n) {
  for (let i = fromIndex; i < Math.min(fromIndex + n, blocks.length); i++) {
    const hex = hexOf(blocks[i]); if (!blockCache.has(hex)) getBlock(hex).catch(() => {});
  }
}
async function serveRange(start, end, m) {
  const { blockSize, blocks, image } = m;
  const total = image.bytes; end = Math.min(end, total - 1);
  const out = new Uint8Array(end - start + 1);
  const firstBlock = Math.floor(start / blockSize), lastBlock = Math.floor(end / blockSize);
  for (let bi = firstBlock; bi <= lastBlock; bi++) {
    const block = await getBlock(hexOf(blocks[bi]));
    const blockStart = bi * blockSize;
    const from = Math.max(start, blockStart) - blockStart;
    const to = Math.min(end, blockStart + block.length - 1) - blockStart;
    out.set(block.subarray(from, to + 1), (blockStart + from) - start);
  }
  prefetch(blocks, lastBlock + 1, 4);
  return { out, total };
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || url.pathname !== IMAGE_PATH) return;
  const range = req.headers.get("range");
  if (!range) return;
  event.respondWith(handleRange(req, range));
});
async function handleRange(req, range) {
  try {
    const m = await loadManifest();
    const total = m.image.bytes;
    const mm = /bytes=(\d+)-(\d*)/.exec(range);
    if (!mm) return new Response("bad range", { status: 416 });
    const start = +mm[1];
    const end = mm[2] === "" ? total - 1 : +mm[2];
    stats.reads++;
    const { out } = await serveRange(start, end, m);
    stats.bytes += out.length;
    return new Response(out, { status: 206, headers: {
      "Content-Type": "application/octet-stream", "Accept-Ranges": "bytes",
      "Content-Length": String(out.length),
      "Content-Range": `bytes ${start}-${start + out.length - 1}/${total}` } });
  } catch (e) { return new Response("κ-block error: " + (e && e.message || e), { status: 502 }); }
}
self.addEventListener("message", (event) => {
  const msg = event.data || {};
  if (msg.type === "kblocks-stats") {
    const avg = stats.blockFetches ? (stats.totalStallMs / stats.blockFetches) : 0;
    const data = { type: "kblocks-stats", ...stats, avgStallMs: +avg.toFixed(2) };
    if (event.source) event.source.postMessage(data);
    else if (event.ports && event.ports[0]) event.ports[0].postMessage(data);
  }
});
