import { startServer, ORIG } from "./holo-serve-fhs.mjs";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
const { port, close } = await startServer();
const require = createRequire(pathToFileURL(ORIG + "/package.json"));
const { chromium } = require("playwright");
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
const errs = [];
page.on("console", (m) => { if (m.type() === "error") errs.push(m.text()); });
page.on("pageerror", (e) => errs.push(String(e)));
await page.goto(`http://127.0.0.1:${port}/holospace.html?app=org.hologram.HoloGuide&bare=1&sw=0`, { waitUntil: "domcontentloaded", timeout: 20000 });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
await sleep(4000);
await page.evaluate(() => { const f = document.querySelector("#frame"); if (f && f.contentWindow) f.contentWindow.location.hash = "#/join"; });
await sleep(1500);
await page.screenshot({ path: "C:/Users/pavel/Desktop/Hologram OS2/system/tools/_book-join.png" });
console.log("errors:", errs.length);
await browser.close(); close();
